### ISSUE TITLE
VERSION file not found - Cannot install

### ISSUE THREAD

**Issue by akall80** [AtsushiSakai/PyJSONViewer#10]
Hello,
    I am installing PyJSONViewer via the following command
`pip install --proxy <MYPROXY> PyJSONViewer`

The error says that VERSION file is missed: actually it does not seem to be packed up (checked via tar.gz download)

I am on Win10, using PyCharm and a dedicated Python 3.7 environment created with Miniconda3.
This happens both from the command line and from PyCharm, of course.

Thanks!
Andrea

Error log:
`
Collecting PyJSONViewer
  Downloading https://files.pythonhosted.org/packages/be/63/deea6ffc40306191fac73abab6e31ccca1ba5f8547c6f5aab71a35bf7cf0/PyJSONViewer-1.4.0.tar.gz (46kB)

    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\MYSELF\miniconda3\envs\MYENV\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\MYSELF\\AppData\\Local\\Temp\\pycharm-packaging\\PyJSONViewer\\setup.py'"'"'; __file__='"'"'C:\\Users\\MYSELF\\AppData\\Local\\Temp\\pycharm-packaging\\PyJSONViewer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\MYSELF\AppData\Local\Temp\pycharm-packaging\PyJSONViewer\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MYSELF\AppData\Local\Temp\pycharm-packaging\PyJSONViewer\setup.py", line 18, in <module>
        from pyjsonviewer import pyjsonviewer
      File "C:\Users\MYSELF\AppData\Local\Temp\pycharm-packaging\PyJSONViewer\pyjsonviewer\pyjsonviewer.py", line 20, in <module>
        VERSION = open(os.path.dirname(os.path.abspath(__file__))+"/../VERSION", "r").readline()
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MYSELF\\AppData\\Local\\Temp\\pycharm-packaging\\PyJSONViewer\\pyjsonviewer/../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by AtsushiSakai** [comment]
@akall80 I updated master codes and release v1.4.1 to fix the problem. In my environments, it seems OK. Could you please check the latest one?

**Comment by akall80** [comment]
@AtsushiSakai now it installs.
But when I run it, it still says that the VERSION file is not available in the final destination

`Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\paramsupport\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\USER\miniconda3\envs\paramsupport\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\miniconda3\envs\paramsupport\lib\site-packages\pyjsonviewer\__main__.py", line 1, in <module>
    from pyjsonviewer.pyjsonviewer import main
  File "C:\Users\USER\miniconda3\envs\paramsupport\lib\site-packages\pyjsonviewer\pyjsonviewer.py", line 20, in <module>
    VERSION = open(os.path.dirname(os.path.abspath(__file__))+"/../VERSION", "r").readline()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\miniconda3\\envs\\paramsupport\\lib\\site-packages\\pyjsonviewer/../VERSION'
`

Please notice that the VERSION file is searched in the parent directory, not in the pyjsonviewer folder

**Comment by AtsushiSakai** [comment]
@akall80 Oh Sorry. I released v1.4.3. Could you please try it again?

**Comment by AtsushiSakai** [comment]
@akall80 Could you please try it again?
