### ISSUE TITLE
Lists Don't Seem to Work

### ISSUE THREAD

**Issue by LionKimbro** [AtsushiSakai/PyJSONViewer#18]
For example, this input:
`[1,2,3]`

**Comment by AtsushiSakai** [comment]
@LionKimbro  Thank you for your report.
Currently, list is shown as space separated  strings:
<img width="815" alt="SS 2021-04-16 at 23 44 29" src="https://user-images.githubusercontent.com/3813847/115041946-ffcdca00-9f0d-11eb-86c7-9f4bc82f3d8a.png">
What is your suggestion?
