### ISSUE TITLE
Make pyjsonviewer callable from python code.

### ISSUE THREAD

**Issue by Ankush-Chander** [AtsushiSakai/PyJSONViewer#33]
Expectation: Ability to visualise json files as well as directly load json objects from within python code.

**Comment by Ankush-Chander** [comment]
Hi @AtsushiSakai,

I have successfully implemented it on my local with minimal changes but wanted to confirm if there is an existing way to achieve the same.
If not, I will create a pull request once the existing PR is reviewed.

Thanks again for the good work you have put in this project.

**Comment by AtsushiSakai** [comment]
Thanks. Your PR is welcome!!.
