### ISSUE TITLE
object has no attribute w

### ISSUE THREAD

**Issue by brandonortiz** [AtsushiSakai/PyJSONViewer#9]
Traceback (most recent call last):
  File "pyjsonviewer.py", line 299, in <module>
    main()
  File "pyjsonviewer.py", line 255, in main
    root.tk.call('wm', 'iconphoto', root.tk.w,
AttributeError: '_tkinter.tkapp' object has no attribute 'w'

This issue is fixed for me by changing root.w to root at pyjsonviewer.py:255

**Comment by esreynaa** [comment]
Had the same issue running pyjsonviewer on Windows 10. Your modification fixed the issue.

**Comment by akall80** [comment]
I've just forked it to solve this issue. https://github.com/akall80/PyJSONViewer
There's another issue with the VERSION file that I am going to solve in the next future

**Comment by esreynaa** [comment]
@akall80 Yeah I had to modify that too in windows. The location it was pointing to was wrong.

**Comment by AtsushiSakai** [comment]
@obra-brandon @akall80 @esreynaa Thank you guys for reporting and I'm sorry for late reply.

**Comment by AtsushiSakai** [comment]
@obra-brandon @akall80 @esreynaa I updated master codes and release v1.4.1 to fix the problems. In my environments, it seems OK. Could you please check the latest one?

**Comment by akall80** [comment]
@AtsushiSakai, with the _w correction now it works. Thanks!

**Comment by AtsushiSakai** [comment]
@akall80 Thank you too!!
